#!/bin/bash

# install Docker
curl -fsSL https://get.docker.com/ | sh

# add current user to the Docker group
sudo usermod -aG docker $USER

# start the docker container
docker container run -d -p 80:80 gluobe/multi-cloud-app:v1
